# https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs
#
#  Variables:
#  GKE_ZONE, GKE_CLUSTER, IMAGE 

# SECRETS USED
# ------------
# SA_EMAIL 
# GOOGLE_APPLICATION_CREDENTIALS (Base64 encoded JSON service account key)
# GKE_PROJECT

# todo
# 1. move app to subfolder and maintain build steps - docker build -f
# 2. create nodejs app to replicate same + show hostname
# 3. create staging & deployment steps

name: Build and Deploy to GKE

on:
  push:
    branches:
      - master
    paths:
      - static-site

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kube
  GKE_ZONE: us-east1-d
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          cd static-site
          docker build -t gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          cd static-site
          docker push gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

      # Set up kustomize
      - name: Set up Kustomize
        run: |
          cd infra
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          cd infra
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE --project $GKE_PROJECT
          ./kustomize edit set image gcr.io/GKE_PROJECT/IMAGE:TAG=gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/gke-test
          kubectl get services -o wide
